# Static Country Seeder Data

COUNTRIES_SEED_DATA = [
    {
        "name": "India",
        "code": "IND",
        "iso2": "IN",
        "iso3": "IND",
        "continent": "Asia",
        "flag_emoji": "🇮🇳",
        "flag_url": "https://flagcdn.com/w320/in.png",
        "region": "South Asia",
        "population": 1428627663,
        "gdp_usd": "$3.75 Trillion",
        "latitude": 20.5937,
        "longitude": 78.9629,
    },
    {
        "name": "United States",
        "code": "USA",
        "iso2": "US",
        "iso3": "USA",
        "continent": "North America",
        "flag_emoji": "🇺🇸",
        "flag_url": "https://flagcdn.com/w320/us.png",
        "region": "North America",
        "population": 339996563,
        "gdp_usd": "$26.95 Trillion",
        "latitude": 37.0902,
        "longitude": -95.7129,
    },
    {
        "name": "China",
        "code": "CHN",
        "iso2": "CN",
        "iso3": "CHN",
        "continent": "Asia",
        "flag_emoji": "🇨🇳",
        "flag_url": "https://flagcdn.com/w320/cn.png",
        "region": "East Asia",
        "population": 1411750000,
        "gdp_usd": "$17.78 Trillion",
        "latitude": 35.8617,
        "longitude": 104.1954,
    },
    {
        "name": "Japan",
        "code": "JPN",
        "iso2": "JP",
        "iso3": "JPN",
        "continent": "Asia",
        "flag_emoji": "🇯🇵",
        "flag_url": "https://flagcdn.com/w320/jp.png",
        "region": "East Asia",
        "population": 124516650,
        "gdp_usd": "$4.21 Trillion",
        "latitude": 36.2048,
        "longitude": 138.2529,
    },
    {
        "name": "Germany",
        "code": "DEU",
        "iso2": "DE",
        "iso3": "DEU",
        "continent": "Europe",
        "flag_emoji": "🇩🇪",
        "flag_url": "https://flagcdn.com/w320/de.png",
        "region": "Western Europe",
        "population": 84482267,
        "gdp_usd": "$4.46 Trillion",
        "latitude": 51.1657,
        "longitude": 10.4515,
    },
    {
        "name": "United Kingdom",
        "code": "GBR",
        "iso2": "GB",
        "iso3": "GBR",
        "continent": "Europe",
        "flag_emoji": "🇬🇧",
        "flag_url": "https://flagcdn.com/w320/gb.png",
        "region": "Western Europe",
        "population": 67736802,
        "gdp_usd": "$3.34 Trillion",
        "latitude": 55.3781,
        "longitude": -3.4360,
    },
    {
        "name": "Brazil",
        "code": "BRA",
        "iso2": "BR",
        "iso3": "BRA",
        "continent": "South America",
        "flag_emoji": "🇧🇷",
        "flag_url": "https://flagcdn.com/w320/br.png",
        "region": "South America",
        "population": 216422446,
        "gdp_usd": "$2.17 Trillion",
        "latitude": -14.2350,
        "longitude": -51.9253,
    },
    {
        "name": "South Africa",
        "code": "ZAF",
        "iso2": "ZA",
        "iso3": "ZAF",
        "continent": "Africa",
        "flag_emoji": "🇿🇦",
        "flag_url": "https://flagcdn.com/w320/za.png",
        "region": "Sub-Saharan Africa",
        "population": 60414495,
        "gdp_usd": "$377.7 Billion",
        "latitude": -30.5595,
        "longitude": 22.9375,
    },
]
